// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataGenerator
{
    public partial class FahrkartenContext : DbContext
    {
        public FahrkartenContext()
        {
        }

        public FahrkartenContext(DbContextOptions<FahrkartenContext> options)
            : base(options)
        {
        }
        public FahrkartenContext(string connection) : this(
            new DbContextOptionsBuilder<FahrkartenContext>()
                .UseOracle(connection)
                .Options)
        { }

        public virtual DbSet<Kartenart> Kartenarts { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Verkauf> Verkaufs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

        }
    }
}