// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataGenerator
{
    [Table("KARTENART")]
    public partial class Kartenart
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("KARTENART_ID")]
        public int KartenartId { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(200)]
        public string Name { get; set; }
        [Column("TAGEGUELTIG")]
        public int? TageGueltig { get; set; }
        [Column("PREIS")]
        public decimal? Preis { get; set; }
        [InverseProperty("KartenartNavigation")]
        public virtual ICollection<Verkauf> Verkaufs { get; set; }
    }
}