// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataGenerator
{
    [Table("STATION")]
    public partial class Station
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("STATION_ID")]
        public int StationId { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(200)]
        public string Name { get; set; }

        [InverseProperty("StationNavigation")]
        public virtual ICollection<Verkauf> Verkaufs { get; set; }
    }
}