// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataGenerator
{
    [Table("VERKAUF")]
    public partial class Verkauf
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("VERKAUF_ID")]
        public int VerkaufId { get; set; }
        [Column("DATUM")]
        public DateTime Datum { get; set; }
        [NotMapped]
        public int Wochentag { get; set; }
        [NotMapped]
        public int Stunde { get; set; }
        [Column("STATION")]
        public int Station { get; set; }
        [Column("KARTENART")]
        public int Kartenart { get; set; }

        [ForeignKey("Kartenart")]
        [InverseProperty("Verkaufs")]
        public virtual Kartenart KartenartNavigation { get; set; }
        [ForeignKey("Station")]
        [InverseProperty("Verkaufs")]
        public virtual Station StationNavigation { get; set; }
    }
}